const { createGlobPatternsForDependencies } = require('@nx/angular/tailwind');
const { join } = require('path');
const { tailwindBaseConfig } = require('../../tailwind.base.config');
const { libContent, ...rest } = tailwindBaseConfig;

/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		join(__dirname, 'src/**/!(*.spec).{ts,html}'),
		join(__dirname, '.storybook/pages/**/*.mdx'),
		__dirname.replace(
			'apps/pmds-hub-storybook',
			'libs/**/src/**/!(*.spec).{ts,html}'
		),
		...createGlobPatternsForDependencies(__dirname),
	],
	safelist: [
		'bg-color-text-primary',
		'bg-color-text-secondary',
		'bg-color-text-tertiary',
		'bg-color-text-disabled',
		'bg-color-text-success',
		'bg-color-text-error',
		'bg-color-text-warning',
		'bg-color-text-info',
		'bg-color-background-default',
		'bg-color-background-alternative',
		'bg-color-background-success',
		'bg-color-background-error',
		'bg-color-background-warning',
		'bg-color-background-info',
		'bg-color-background-overlay-primary',
		'bg-color-background-overlay-secondary',
		'bg-color-surface-primary',
		'bg-color-surface-secondary',
		'bg-color-surface-tertiary',
		'bg-color-surface-hover',
		'bg-color-surface-selected',
		'bg-color-surface-disabled',
		'bg-color-icon-default',
		'bg-color-icon-disabled',
		'bg-color-icon-alternative',
		'bg-color-icon-action',
		'bg-color-icon-success',
		'bg-color-icon-error',
		'bg-color-icon-warning',
		'bg-color-icon-info',
		'bg-color-action-main-default',
		'bg-color-action-on-main-default',
		'bg-color-action-main-hover',
		'bg-color-action-main-selected',
		'bg-color-action-alternative-default',
		'bg-color-action-on-alternative-default',
		'bg-color-action-disabled',
		'bg-color-action-on-disabled',
		'bg-color-border-default',
		'bg-color-border-focus',
		'bg-color-border-disabled',
		'bg-color-border-alternative',
		'bg-color-border-active',
		'bg-color-border-decorative',
		'bg-color-border-info',
		'bg-color-border-success',
		'bg-color-border-warning',
		'bg-color-border-error',
		'bg-color-button-secondary-default',
		'bg-color-button-secondary-on-default',
		'bg-color-button-secondary-on-hover',
		'bg-color-button-secondary-on-pressed',
		'bg-color-button-secondary-on-disabled',
		'bg-color-tooltip',
		'bg-color-background-funnel',
		'bg-color-support-01',
		'bg-color-support-02',
		'bg-color-support-03',
		'bg-color-support-04',
		'bg-color-support-05',
		'bg-color-support-06',
		'bg-color-support-07',
		'bg-color-support-08',
		'bg-color-support-09',
		'bg-color-support-10',
	],
	...rest,
};
